### ISSUE TITLE
libraries/fc/src/network/ntp.cpp causing build errrors

### ISSUE THREAD

**Issue by gileadmcgee** [bitshares/bitshares1-core#273]
unable to build in windows 7 x64 or ubuntu 14.04 x64.  error on both is 

Error   247 error C3861: 'ntohl': identifier not found  C:\bitshares\bitshares_toolkit\libraries\fc\src\network\ntp.cpp 40  1   fc

P.S.  New to this stuff, please let me know if I'm doing it wrong.
